family: sd
sd:
  variant: instruct_pix2pix
  v2_highres: false
  prompt: ''
  im_path: instruct_pix2pix
  scale: null
  text_cfg_scale: 7.5
  image_cfg_scale: 1.5
  precision: autocast
training_data_dir: zero123_nerf_output
lr: 0.05
n_steps: 1000
vox:
  model_type: V_SD
  bbox_len: 1.0
  grid_size:
  - 100
  - 100
  - 100
  step_ratio: 0.5
  density_shift: -1.0
  ray_march_weight_thres: 0.0001
  c: 4
  blend_bg_texture: false
  bg_texture_hw: 4
vox_warmstart_ckpt: experiments/exp_wild/scene-spyro-index-0_scale-100.0_train-view-True_view-weight-10000_depth-smooth-wt-10000.0_near-view-wt-10000.0/ckpt/step_10000.pt
pose:
  rend_hw: 32
  FoV: 49.1
  R: 2.0
  up: z
emptiness_scale: 10
emptiness_weight: 0
emptiness_step: 0.5
emptiness_multiplier: 20.0
grad_accum: 1
train_view: true
depth_smooth_weight: 0.0
near_view_weight: 1000.0
view_weight: 10000.0
var_red: true
