family: sd
sd:
  variant: instruct_pix2pix
  v2_highres: false
  prompt: ''
  im_path: nerf_for_instruct_pix2pix
  scale: null
  text_cfg_scale: 7.5
  image_cfg_scale: 1.5
  precision: autocast
training_data_dir: views_whole_sphere/8ff7f1f2465347cd8b80c9b206c2781e
lr: 0.05
n_steps: 10000
vox:
  model_type: V_SD
  bbox_len: 1.0
  grid_size:
  - 100
  - 100
  - 100
  step_ratio: 0.5
  density_shift: -1.0
  ray_march_weight_thres: 0.0001
  c: 4
  blend_bg_texture: false
  bg_texture_hw: 4
vox_warmstart_ckpt: null
pose:
  rend_hw: 32
  FoV: 49.1
  R: 2.0
  up: z
depth_smooth_weight: 0.0
near_view_weight: 0.0
view_weight: 10000.0
emptiness_weight: 0
emptiness_scale: 10
emptiness_step: 0.5
emptiness_multiplier: 20.0
grad_accum: 1
save_step_percentage: 1
